services:
  fastapi-app:
    build:
      context: ./  # Current directory (where Dockerfile and requirements.txt are located)
      dockerfile: Dockerfile  # Explicitly specify the Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app  # Mount for live reload during development
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload  # For development
    restart: unless-stopped  # Auto-restart unless manually stopped
